{"timestamp":"2025-10-13T23:56:01.904525Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-13T23:56:01.905935Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/budget_municipal_etl.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-13T23:56:01.929957Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/budget_municipal_etl.py","lineno":9,"logger":"py.warnings"}
{"timestamp":"2025-10-13T23:56:01.965999Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:01.966800Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:01.967199Z","level":"info","event":"Current task name:load_data","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:01.967579Z","level":"info","event":"Dag name:budget_municipal_etl","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:01.969485Z","level":"info","event":"Starting data loading to PostgreSQL database","logger":"root","filename":"budget_municipal_etl.py","lineno":252}
{"timestamp":"2025-10-13T23:56:01.989254Z","level":"info","event":"Loading data from Feuil1 to database","logger":"root","filename":"budget_municipal_etl.py","lineno":267}
{"timestamp":"2025-10-13T23:56:02.928745Z","level":"info","event":"Inserted 2376 records from Feuil1","logger":"root","filename":"budget_municipal_etl.py","lineno":343}
{"timestamp":"2025-10-13T23:56:02.943666Z","level":"info","event":"Loading data from Feuil2 to database","logger":"root","filename":"budget_municipal_etl.py","lineno":267}
{"timestamp":"2025-10-13T23:56:02.966651Z","level":"info","event":"Inserted 5 records from Feuil2","logger":"root","filename":"budget_municipal_etl.py","lineno":343}
{"timestamp":"2025-10-13T23:56:02.974295Z","level":"info","event":"Loading data from Feuil3 to database","logger":"root","filename":"budget_municipal_etl.py","lineno":267}
{"timestamp":"2025-10-13T23:56:02.990568Z","level":"info","event":"Inserted 7 records from Feuil3","logger":"root","filename":"budget_municipal_etl.py","lineno":343}
{"timestamp":"2025-10-13T23:56:03.019513Z","level":"info","event":"Combined dataset saved to /opt/airflow/processed/combined_municipal_budget.csv","logger":"root","filename":"budget_municipal_etl.py","lineno":387}
{"timestamp":"2025-10-13T23:56:03.025556Z","level":"error","event":"Error during loading: (psycopg2.errors.UndefinedTable) relation \"etl_audit\" does not exist\nLINE 2:         INSERT INTO etl_audit (dag_run_id, task_id, executio...\n                            ^\n\n[SQL: \n        INSERT INTO etl_audit (dag_run_id, task_id, execution_date, status, records_processed)\n        VALUES (%(dag_run_id)s, %(task_id)s, %(execution_date)s, %(status)s, %(records_processed)s)\n        ]\n[parameters: {'dag_run_id': 'budget_municipal_etl', 'task_id': 'load_data', 'execution_date': DateTime(2025, 10, 13, 23, 55, 6, tzinfo=Timezone('UTC')), 'status': 'SUCCESS', 'records_processed': 2388}]\n(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"root","filename":"budget_municipal_etl.py","lineno":428}
{"timestamp":"2025-10-13T23:56:03.040606Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.UndefinedTable) relation \"etl_audit\" does not exist\nLINE 2:         INSERT INTO etl_audit (dag_run_id, task_id, executio...\n                            ^\n\n[SQL: \n        INSERT INTO etl_audit (dag_run_id, task_id, execution_date, status, records_processed)\n        VALUES (%(dag_run_id)s, %(task_id)s, %(execution_date)s, %(status)s, %(records_processed)s)\n        ]\n[parameters: {'dag_run_id': 'budget_municipal_etl', 'task_id': 'load_data', 'execution_date': DateTime(2025, 10, 13, 23, 55, 6, tzinfo=Timezone('UTC')), 'status': 'SUCCESS', 'records_processed': 2388}]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/budget_municipal_etl.py","lineno":410,"name":"load_budget_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py","lineno":334,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1577,"name":"_execute_clauseelement"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"UndefinedTable","exc_value":"relation \"etl_audit\" does not exist\nLINE 2:         INSERT INTO etl_audit (dag_run_id, task_id, executio...\n                            ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-13T23:56:03.067304Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.067928Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.068489Z","level":"info","event":"Task:<Task(PythonOperator): load_data>","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.068889Z","level":"info","event":"Failure caused by (psycopg2.errors.UndefinedTable) relation \"etl_audit\" does not exist","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.069269Z","level":"info","event":"LINE 2:         INSERT INTO etl_audit (dag_run_id, task_id, executio...","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.069570Z","level":"info","event":"                            ^","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.069841Z","level":"info","event":"","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.070115Z","level":"info","event":"[SQL:","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.070408Z","level":"info","event":"        INSERT INTO etl_audit (dag_run_id, task_id, execution_date, status, records_processed)","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.070736Z","level":"info","event":"        VALUES (%(dag_run_id)s, %(task_id)s, %(execution_date)s, %(status)s, %(records_processed)s)","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.071031Z","level":"info","event":"        ]","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.071318Z","level":"info","event":"[parameters: {'dag_run_id': 'budget_municipal_etl', 'task_id': 'load_data', 'execution_date': DateTime(2025, 10, 13, 23, 55, 6, tzinfo=Timezone('UTC')), 'status': 'SUCCESS', 'records_processed': 2388}]","logger":"task.stdout"}
{"timestamp":"2025-10-13T23:56:03.071611Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"task.stdout"}
